experiment_name: ur3_blood_pipe_vision_wrist_safe_dreamer
logdir: null
seed: 0
deterministic_run: false
device: cuda:0
model_preset: size12M

buffer:
  batch_size: 2
  batch_length: 16
  max_size: 50000
  storage_device: cpu

trainer:
  total_steps: 510000
  pretrain_updates: 0
  eval_every: 10000
  eval_episode_num: 4
  train_ratio: 8
  video_pred_log: false
  params_hist_log: false
  update_log_every: 5000
  save_every: 100000
  policy_save_every: 50000
  action_repeat: 1
  start_after_steps: 64

env:
  task: Isaac-Ur3-Blood-Pipe-Vision-Wrist-Direct-v0
  num_envs: 4
  eval_num_envs: 1
  cfg_overrides:
    reward_include_safety_penalties: false
  encoder:
    mlp_keys: position
    cnn_keys: image
  decoder:
    mlp_keys: position
    cnn_keys: image

model:
  rep_loss: dreamer
  compile: false
  safety:
    enabled: true
    cost_limit: 0.02
    lambda_init: 0.0
    lambda_lr: 0.5
    lambda_max: 30.0
  encoder:
    mlp_keys: position
    cnn_keys: image
  decoder:
    mlp_keys: position
    cnn_keys: image
